import type { ExecutiveReport } from "@/lib/agents/types";

export type RenderedIssue = { title: string; body: string };

function bullets(items: string[]): string {
  if (items.length === 0) return "_None._";
  return items.map((i) => `- ${i}`).join("\n");
}

/**
 * Deterministically render an approved executive report as a GitHub issue.
 * Pure string assembly — no model call — so the published artifact always
 * matches the approved report exactly.
 */
export function renderGitHubIssue(report: ExecutiveReport): RenderedIssue {
  const title = `AI Workflow Audit: ${report.taskName}`;

  const findings =
    report.findings.length > 0
      ? report.findings
          .map((f) => `- **${f.title}** (${f.severity}): ${f.detail}`)
          .join("\n")
      : "_No material findings._";

  const workflow =
    report.recommendedWorkflow.length > 0
      ? report.recommendedWorkflow
          .map((s) => `${s.step}. **${s.action}** — ${s.reason}`)
          .join("\n")
      : "_None._";

  const sections: string[] = [
    `# ${title}`,
    "## Executive Summary",
    report.executiveSummary,
    "## What Happened",
    report.whatHappened,
    "## Primary Findings",
    findings,
    "## Improved Prompt",
    "```text\n" + report.improvedPrompt + "\n```",
    "## Recommended Context Bundle",
    bullets(report.recommendedContextBundle),
    "## Recommended Workflow",
    workflow,
    "## Verification Plan",
    bullets(report.verificationPlan),
  ];

  if (report.estimatedEfficiency) {
    sections.push(
      "## Estimated Efficiency Improvement",
      `_Estimate_ — ${report.estimatedEfficiency.summary}\n\nBasis: ${report.estimatedEfficiency.basis}`,
    );
  }

  sections.push(
    "## Reusable Playbook",
    `**${report.reusablePlaybook.name}**\n\n${report.reusablePlaybook.content}`,
    "## Methodology and Limitations",
    report.methodologyAndLimitations,
    "\n---\n_Generated by Mizan — an AI enablement agency for engineering teams._",
  );

  return { title, body: sections.join("\n\n") };
}
